//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace commandersbattle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("commandersbattle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _36832193 {
            get {
                object obj = ResourceManager.GetObject("36832193", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _368321931 {
            get {
                object obj = ResourceManager.GetObject("368321931", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _460_spartan_or_trojan_mascot_with_helmet_spear_and_cape_vector_clipart_image {
            get {
                object obj = ResourceManager.GetObject("460-spartan-or-trojan-mascot-with-helmet-spear-and-cape-vector-clipart-image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Adsız {
            get {
                object obj = ResourceManager.GetObject("Adsız", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Adsız2 {
            get {
                object obj = ResourceManager.GetObject("Adsız2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb {
            get {
                object obj = ResourceManager.GetObject("cb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_illustration_of_knight_with_lance_riding_horse_isolated_on_white_66831094 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-illustration-of-knight-with-lance-riding-horse-isolated-on-white-6683" +
                        "1094", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_illustration_of_knight_with_lance_riding_horse_isolated_on_white_668310941 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-illustration-of-knight-with-lance-riding-horse-isolated-on-white-6683" +
                        "10941", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_spartan_21573073 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-spartan-21573073", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_spartan_215730731 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-spartan-215730731", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_spartan_21640213 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-spartan-21640213", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_spartan_216402131 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-spartan-216402131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_photo_the_picture_shows_the_battle_silhouettes_of_soldiers_depicted_in_the_haze_on_the_background_of_the_66707896 {
            get {
                object obj = ResourceManager.GetObject("stock-photo-the-picture-shows-the-battle-silhouettes-of-soldiers-depicted-in-the-" +
                        "haze-on-the-background-of-the-66707896", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_greek_spartan_or_roman_soldier_mascot_holding_a_shield_and_sword_112275224 {
            get {
                object obj = ResourceManager.GetObject("stock-vector-greek-spartan-or-roman-soldier-mascot-holding-a-shield-and-sword-112" +
                        "275224", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_horizontal_vector_illustration_of_battle_fighting_swordsmen_spearmen_and_cavalry_in_the_battle_135651047 {
            get {
                object obj = ResourceManager.GetObject("stock-vector-horizontal-vector-illustration-of-battle-fighting-swordsmen-spearmen" +
                        "-and-cavalry-in-the-battle-135651047", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_medieval_knight_horseman_silhouettes_riding_in_battle_field_warfare_illustration_background_vector_120334657 {
            get {
                object obj = ResourceManager.GetObject("stock-vector-medieval-knight-horseman-silhouettes-riding-in-battle-field-warfare-" +
                        "illustration-background-vector-120334657", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_medieval_knight_horseman_silhouettes_riding_in_battle_field_warfare_illustration_background_vector_132235982 {
            get {
                object obj = ResourceManager.GetObject("stock-vector-medieval-knight-horseman-silhouettes-riding-in-battle-field-warfare-" +
                        "illustration-background-vector-132235982", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_spartan_mascot_body_with_spear_and_shield_vector_illustration_111894437 {
            get {
                object obj = ResourceManager.GetObject("stock-vector-spartan-mascot-body-with-spear-and-shield-vector-illustration-111894" +
                        "437", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_spartan_trojan_mascot_vector_with_sword_and_shield_85974835 {
            get {
                object obj = ResourceManager.GetObject("stock-vector-spartan-trojan-mascot-vector-with-sword-and-shield-85974835", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stock_vector_spartan_trojan_mascot_vector_with_sword_and_shield_859748351 {
            get {
                object obj = ResourceManager.GetObject("stock-vector-spartan-trojan-mascot-vector-with-sword-and-shield-859748351", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tarihin_altin_insanlari {
            get {
                object obj = ResourceManager.GetObject("tarihin_altin_insanlari", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_5 {
            get {
                object obj = ResourceManager.GetObject("Untitled-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yonler {
            get {
                object obj = ResourceManager.GetObject("yonler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
